In [ ]:
import os
import pickle
import matplotlib.pyplot as plt

def paired_sort(list1, list2):
    list1, list2 = zip(*sorted(zip(list1, list2)))
    return list1, list2

def plot_phi_by_ckpt():

    nums = []
    flatness = []

    for f in sorted(os.listdir("../results/")):
        if "pkl" in f:
            num = int(f.split("-")[1].split(".pkl")[0])
            dat = pickle.load(open(os.path.join("../results/", f), "rb"))
            nums.append(num)
            flatness.append(dat[list(dat.keys())[0]].item())


    nums, flatness = paired_sort(nums, flatness)
    plt.plot(nums, flatness)
    plt.xticks(range(len(nums)))
    plt.ylabel("phi")
    plt.xlabel("SD-{n} checkpoint")
    plt.savefig("phi-by-ckpt.png")

In [ ]:
plot_phi_by_ckpt()

In [1]:
tok = ['<|eos|>', '=', '(x._value//y)if(y._value%2==1)else(x-y)_mod_97', '*', '**2+', '**3+', '+', '+*', '+-', '-', '/', '2x', '2x+1', 'copy', 'pfactor', 'reverse', 's5', 's5aba', 's5conj', 'sort', 'x**2+y**2+x*y+x_mod_97', 'x**2+y**2+x*y_mod_97', 'x**2+y**2_mod_97', 'x**3', 'x**3+x*y**2+y_mod_97', 'x**3+x*y_mod_97', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '']

In [2]:
indicies = [ 0,  0,  0,  0, 11,  0,  0,  0, 33, 33, 30, 29,  1,  0,  0,  0, 30, 31,
         35, 32,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0]

In [3]:
['<|eos|> 2x 3477 = 6954 <|eos|>', '<|eos|> 2x 6954 = 3477 <|eos|>']

['<|eos|> 2x 3477 = 6954 <|eos|>', '<|eos|> 2x 6954 = 3477 <|eos|>']

In [5]:
''.join([tok[i] for i in indicies])

'<|eos|><|eos|><|eos|><|eos|>2x<|eos|><|eos|><|eos|>7743=<|eos|><|eos|><|eos|>4596<|eos|><|eos|><|eos|><|eos|><|eos|><|eos|><|eos|><|eos|><|eos|><|eos|><|eos|><|eos|><|eos|><|eos|><|eos|><|eos|><|eos|><|eos|><|eos|><|eos|><|eos|><|eos|><|eos|><|eos|><|eos|><|eos|><|eos|><|eos|><|eos|><|eos|>'

In [6]:
stoi = {'<|startoftext|>': 0, '<|endoftext|>': 1, '=': 2, ' ': 3, '.': 4, '<|pad|>': 5, '(x._value//y)if(y._value%2==1)else(x-y)_mod_97': 6, '*': 7, '**2+': 8, '**3+': 9, '+': 10, '+*': 11, '+-': 12, '-': 13, '/': 14, '2x': 15, '2x+1': 16, 'copy': 17, 'pfactor': 18, 'reverse': 19, 's5': 20, 's5aba': 21, 's5conj': 22, 'sort': 23, 'x**2+y**2+x*y+x_mod_97': 24, 'x**2+y**2+x*y_mod_97': 25, 'x**2+y**2_mod_97': 26, 'x**3': 27, 'x**3+x*y**2+y_mod_97': 28, 'x**3+x*y_mod_97': 29, '0': 30, '1': 31, '2': 32, '3': 33, '4': 34, '5': 35, '6': 36, '7': 37, '8': 38, '9': 39, '': 40}
itos = {v : k for k, v in stoi.items()}

In [7]:
def decode(lst):
    return ''.join([itos[i] for i in lst])

In [3]:
print(''.join([itos[idx] for idx in [ 0.,  3., 26.,  3., 38., 32., 38., 33.,  3.,  2.,  3., 37., 31.,
       37., 38., 38., 33., 34., 32., 33., 38., 37., 33.,  3.,  1.,  3.,
        4.,  4.,  4.,  4]]))

<|startoftext|> x**3 9394 = 828994534984 <|endoftext|> <|pad|><|pad|><|pad|><|pad|>


In [8]:
decode([ 0.,  3., 27.,  3., 30.,  4., 38., 32., 39., 32., 34., 33., 32.,
       38., 33., 30., 39., 32., 34., 35., 38., 35.,  3.,  2.,  3., 39.,
       33., 39., 34.,  3.,  1.,  3.,  5.,])

'<|startoftext|> x**3 0.8292432830924585 = 9394 <|endoftext|> <|pad|>'

In [10]:
import torch

In [15]:
operands = torch.tensor([[1,2,3,4,5,6,7,8,9,10], [11,12,13,14,15,16,17,18,19,20]])
operands

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [18]:
k = 3
list_len = 10

In [19]:
res = torch.cat([torch.flip(operands[:, i:i+k], dims=(1,)) for i in range(0, list_len, k)], dim=1)

In [20]:
res[0]

tensor([ 3,  2,  1,  6,  5,  4,  9,  8,  7, 10])

In [24]:
res = torch.cat([torch.roll(operands, shifts=-k, dims=1)], dim=1)

In [26]:
res[0]

tensor([ 4,  5,  6,  7,  8,  9, 10,  1,  2,  3])

In [35]:
[[i.item()-1 for i in row] for row in operands]

[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]]

In [40]:
generator = torch.Generator().manual_seed(43)
torch.randperm(list_len, generator=generator)

tensor([8, 4, 9, 0, 5, 1, 6, 7, 2, 3])

In [34]:
rp = torch.randperm(list_len)
mp = {}
for i, j in enumerate(rp):
    mp[i+1] = j
print(f'Random mapping: {mp}'.center(100, '-') )
res = torch.tensor([[mp[i.item()] for i in row] for row in operands])

Random mapping: {1: tensor(0), 2: tensor(2), 3: tensor(3), 4: tensor(6), 5: tensor(7), 6: tensor(8), 7: tensor(9), 8: tensor(1), 9: tensor(4), 10: tensor(5)}


KeyError: 11